version: '3.7'

services:
    db:
        image: postgres:10.1-alpine
        ports:
          - "5432:5432"
    web:
        build: .
        volumes: 
            - .:/app/
        ports:
            - "8000:8000"
        depends_on: 
            - db